import { GATEWAY_RESTART_REPLACEMENT_TIMEOUT_MS } from "../../infra/gateway-shutdown-budget.js";

export const DEFAULT_RESTART_HEALTH_TIMEOUT_MS = GATEWAY_RESTART_REPLACEMENT_TIMEOUT_MS;

export const DEFAULT_RESTART_HEALTH_DELAY_MS = 500;
export const DEFAULT_RESTART_HEALTH_ATTEMPTS = Math.ceil(
  DEFAULT_RESTART_HEALTH_TIMEOUT_MS / DEFAULT_RESTART_HEALTH_DELAY_MS,
);
