import { statSync } from "node:fs";
import { resolve } from "node:path";
import { stateStartupCorpusTestFiles } from "../../test/vitest/vitest.startup-corpus-paths.mjs";

// Complete process/lifecycle proofs stay outside PR CI. Main retains runtime
// owners; manual/release validation also retains the tooling owner.
// Keep this explicit: E2E-named package and browser boundary tests stay on PRs.
export const CI_PROOF_TEST_FILES = [
  "extensions/browser/src/browser/extension-install.native-host.e2e.test.ts",
  "src/gateway/server.codex-failure-recovery.test.ts",
  "test/e2e/qa-lab/plugins/discord-show-widget-contextual-presenter.e2e.test.ts",
  "test/e2e/qa-lab/runtime/sessions-send-visible-child.product-proof.e2e.test.ts",
  "test/scripts/doctor-config-preflight-plugin-index.built-cli.e2e.test.ts",
  "test/scripts/frv.release.test.ts",
  "test/scripts/install-ps1.release.test.ts",
  "test/scripts/sqlite-sessions-transcripts-flip-proof.built-cli.e2e.test.ts",
  "test/scripts/sqlite-sessions-transcripts-flip-proof.e2e.test.ts",
] as const;

const proofTestFiles = new Set<string>(CI_PROOF_TEST_FILES);

export function isCiProofTestFile(file: string): boolean {
  return proofTestFiles.has(file);
}

// Runtime integration and released-state matrices retain their canonical Vitest
// owners, but automatic CI runs them only when the test itself changes.
export const RELEASE_ONLY_RUNTIME_TEST_FILES = [
  "src/agents/agent-bundle-mcp-retention.test.ts",
  "src/agents/harness/acp-native-execution.process.test.ts",
  "src/agents/mcp-stdio-client.cleanup.real.test.ts",
  "src/agents/worktrees/service.exact-state-races.test.ts",
  "src/cli/capability-web-output.process.test.ts",
  "src/cli/gateway-backed-exit.process.test.ts",
  "src/cli/gateway-cli/pre-bootstrap.process.test.ts",
  "src/cli/help-exit.process.test.ts",
  "src/cli/plugins-authoring.process.test.ts",
  "src/cli/skills-cli.sag.process.test.ts",
  "src/commands/doctor-config-flow.automatic-migrations.test.ts",
  "src/commands/doctor-config-flow.include-refusal.test.ts",
  "src/commands/doctor-config-flow.test.ts",
  "src/commands/doctor-config-preflight.container-upgrade.test.ts",
  "src/commands/doctor-config-preflight.pristine.process.test.ts",
  "src/commands/doctor-config-preflight.process.test.ts",
  "src/commands/doctor-config-preflight.refusal.process.test.ts",
  "src/commands/doctor-config-preflight.test.ts",
  "src/commands/doctor-model-metadata-corruption.persistence.test.ts",
  "src/commands/doctor-plugin-install-config.process.test.ts",
  "src/commands/doctor-session-sqlite.memory.test.ts",
  "src/commands/doctor-state-migrations.test.ts",
  "src/commands/doctor/shared/missing-configured-plugin-install.integration.test.ts",
  "src/config/sessions/session-cold-storage.test.ts",
  "src/flows/doctor-health.managed-admission.test.ts",
  "src/flows/doctor-health.managed-approvals.test.ts",
  "src/flows/doctor-health.managed-settlement.test.ts",
  "src/flows/doctor-health.test.ts",
  "src/gateway/gateway-auth-recovery.test.ts",
  "src/gateway/gateway-route-model-reuse.test.ts",
  "src/gateway/gateway.chat-redaction.test.ts",
  "src/gateway/server-channels.ownership.test.ts",
  "src/gateway/server-methods/models-dispatch.lifecycle.integration.test.ts",
  "src/gateway/server-methods/models-list.native-lifecycle.integration.test.ts",
  "src/gateway/server-plugins.lifecycle.test.ts",
  "src/gateway/server.acp-native-model.product.test.ts",
  "src/gateway/server.catalog-startup.test.ts",
  "src/gateway/server.cron.test.ts",
  "src/gateway/server.labs-hot-reload.test.ts",
  "src/gateway/server.message-buffer-caption.test.ts",
  "src/gateway/server.sessions.archive-worktree-lifecycle.test.ts",
  "src/gateway/server.sessions.create.projects.test.ts",
  "src/gateway/server.sessions.delete-worktree-lifecycle.test.ts",
  "src/gateway/session-row-projection.keyed-marks.benchmark.test.ts",
  "src/gateway/worker-environments/live-chat.test.ts",
  "src/gateway/worker-environments/node-workspace-transfer-retention.test.ts",
  "src/gateway/worker-environments/placement-abandon-lifecycle.test.ts",
  "src/gateway/worker-environments/placement-dispatch-prepared.test.ts",
  "src/gateway/worker-environments/placement-dispatch-staged-results.test.ts",
  "src/gateway/worker-environments/provider-provisioning.cancellation.test.ts",
  "src/gateway/worker-environments/provider-reconciliation.test.ts",
  "src/gateway/worker-environments/service-lifetime.test.ts",
  "src/gateway/worker-environments/store-node-enrollment.test.ts",
  "src/gateway/worker-environments/workspace-result-repository.test.ts",
  "src/infra/outbound/delivery-queue.recovery.test.ts",
  "src/infra/state-migrations.media-persistence.large-corpus.test.ts",
  "src/infra/state-migrations.test.ts",
  "src/infra/update-candidate-canary.integration.test.ts",
  "src/infra/update-managed-service-handoff-foreground.test.ts",
  "src/infra/update-managed-service-handoff-native-lifecycle.test.ts",
  "src/infra/update-managed-service-handoff-recovery-launchd.test.ts",
  "src/infra/update-managed-service-handoff-recovery-systemd.test.ts",
  "src/infra/update-managed-service-triage.test.ts",
  "src/node-host/node-worker-supervisor.container.test.ts",
  "src/node-host/node-worker-supervisor.recovery.test.ts",
  "src/plugins/post-core-dependency-health.integration.test.ts",
  "src/plugins/provider-auth-choice.npm-installed.test.ts",
  "src/process/supervisor/adapters/child.service-lifecycle.test.ts",
  "src/snapshot/git-backup-streaming.test.ts",
  "src/state/openclaw-database-preflight.lifecycle.test.ts",
  "test/cron-message-read.integration.test.ts",
  "test/plugins/codex-model-catalog.gateway.test.ts",
  "test/scripts/bench-sqlite-reliability.test.ts",
  "test/scripts/check-openclaw-package-tarball.bundled-mcp.test.ts",
  "test/scripts/ci-changed-node-test-plan.integration.test.ts",
  "test/scripts/ci-linux-git.test.ts",
  "test/scripts/full-release-validation-at-sha.test.ts",
  "test/scripts/package-acceptance-workflow.test.ts",
  "test/scripts/pr-merge-admission.test.ts",
  "test/scripts/pr-merge-correction.test.ts",
  "test/scripts/pr-merge-outcome.test.ts",
  "test/scripts/pr-merge-receipt.test.ts",
  "test/scripts/pr-merge-recovery.test.ts",
  "test/scripts/pr-merge-rest.test.ts",
  "test/scripts/pr-worktree-interruption.test.ts",
  "test/scripts/pr-worktree-provision.test.ts",
  "test/scripts/run-vitest-bounded.test.ts",
  "test/scripts/run-vitest-state-cleanup.test.ts",
  "test/scripts/test-projects-empty-native.test.ts",
  ...stateStartupCorpusTestFiles,
] as const;

const releaseOnlyRuntimeTestFiles = new Set<string>(RELEASE_ONLY_RUNTIME_TEST_FILES);

export function isReleaseOnlyRuntimeTestFile(file: string): boolean {
  return releaseOnlyRuntimeTestFiles.has(file);
}

// Complete integration proofs run hourly on main and in full release validation.
// PRs opt in when an edited test or its source owner resolves to the proof.
const PR_EXEMPT_RUNTIME_TEST_FILES = [
  "extensions/acpx/src/runtime-mcp.process.test.ts",
  "extensions/acpx/src/runtime-owner.process.test.ts",
  "extensions/codex/src/node-exec-server.test.ts",
  "extensions/crabbox/src/crabbox-worker-warm-image.test.ts",
  "extensions/discord/src/voice/realtime-playback-pcm.integration.test.ts",
  "extensions/imessage/src/send.test.ts",
  "extensions/matrix/doctor-contract-api.account-state.test.ts",
  "extensions/matrix/src/outbound.currentness.integration.test.ts",
  "extensions/mattermost/src/mattermost/monitor-posts.thread-history.test.ts",
  "extensions/memory-core/src/memory/index.test.ts",
  "extensions/memory-core/src/memory/manager-candidate-repair.test.ts",
  "extensions/memory-core/src/memory/manager-keyword-retrieval.test.ts",
  "extensions/memory-core/src/memory/manager-search-monotonicity.test.ts",
  "extensions/memory-core/src/memory/manager-search-orchestration.test.ts",
  "extensions/memory-core/src/memory/manager-session-update-race.test.ts",
  "extensions/memory-core/src/memory/manager.reindex-recovery.test.ts",
  "extensions/qa-lab/src/suite-process-lifecycle.test.ts",
  "extensions/signal/src/client-container.handshake.loopback.test.ts",
  "extensions/slack/src/monitor/http-handler.test.ts",
  "extensions/telegram/src/action-runtime.test.ts",
  "extensions/telegram/src/bot-message-context.body.test.ts",
  "extensions/telegram/src/bot-message-context.dm-session.test.ts",
  "extensions/telegram/src/bot-message-dispatch.progress-command-detail.telegram-http.test.ts",
  "extensions/zalouser/src/zalo-js.listener.test.ts",
  "src/acp/client.process.test.ts",
  "src/agents/agent-command-local.test.ts",
  "src/agents/embedded-agent-runner/run-orchestrator.projection.test.ts",
  "src/agents/embedded-agent-runner/run/attempt-session-replay.test.ts",
  "src/agents/sessions/agent-session-code-mode-source.test.ts",
  "src/agents/sessions/agent-session-tool-result-redaction.test.ts",
  "src/agents/worktrees/service.acceleration.test.ts",
  "src/agents/worktrees/service.diagnostics.test.ts",
  "src/agents/worktrees/service.profiles.test.ts",
  "src/auto-reply/dispatch.block-streaming-recovery.test.ts",
  "src/claws/lifecycle-remove-approvals.test.ts",
  "src/cli/agent-session-affinity.process.test.ts",
  "src/cli/cli-process-child.test-helpers.test.ts",
  "src/cli/doctor-output.process.test.ts",
  "src/cli/gateway-cli/run-loop.model-acquisition.process.test.ts",
  "src/cli/mcp-cli.test.ts",
  "src/cli/program/root-command-descriptions.test.ts",
  "src/cli/run-main.exit.test.ts",
  "src/cli/update-cli.package-lifecycle.test.ts",
  "src/cli/update-cli.service-authority.test.ts",
  "src/cli/update-cli.test.ts",
  "src/cli/update-cli/update-command-admission-schema.test.ts",
  "src/cli/update-cli/update-command-contention.test.ts",
  "src/cli/update-cli/update-command-plugins.degradation.test.ts",
  "src/cli/update-cli/update-command-rollback-executor.test.ts",
  "src/cli/update-dry-run-state.process.test.ts",
  "src/commands/backup-capture-privacy.test.ts",
  "src/commands/doctor-config-preflight.pending-read.test.ts",
  "src/commands/doctor-config-preflight.plugin-deferral.test.ts",
  "src/commands/doctor-config-preflight.state-lifecycle.test.ts",
  "src/commands/doctor-session-canonical-keys.memory.test.ts",
  "src/commands/doctor-skill-workshop-collection-backups.test.ts",
  "src/commands/doctor-skill-workshop-relocation.atomicity.test.ts",
  "src/commands/doctor-skill-workshop-sqlite.relocation-conflicts.test.ts",
  "src/commands/doctor-skill-workshop-workspace.test.ts",
  "src/commands/models/model-selection.runtime.test.ts",
  "src/config/io.runtime-async.test.ts",
  "src/config/sessions/session-accessor.sqlite-archive-session.test.ts",
  "src/config/sessions/session-accessor.sqlite-branches.test.ts",
  "src/config/sessions/session-accessor.sqlite-maintenance-worker.test.ts",
  "src/config/sessions/session-accessor.sqlite-prepared-admission.test.ts",
  "src/config/sessions/session-history-budget-owner.test.ts",
  "src/config/sessions/session-history-eviction.admission.test.ts",
  "src/config/sessions/session-history-eviction.test.ts",
  "src/config/state-corpus-fixture-lifetime.test.ts",
  "src/cron/service/owner-hardening.test.ts",
  "src/entry.memory-json.test.ts",
  "src/gateway/control-ui-session-prs-branch.test.ts",
  "src/gateway/gateway-cli-plugin-routing.test.ts",
  "src/gateway/gateway-code-mode-clock.test.ts",
  "src/gateway/gateway-concurrent-streams.test.ts",
  "src/gateway/github-personal-publication.test.ts",
  "src/gateway/github-publication-transcript.test.ts",
  "src/gateway/internal-source-reply-persistence.test.ts",
  "src/gateway/link-understanding.product.test.ts",
  "src/gateway/managed-image-attachments.sqlite-visibility.test.ts",
  "src/gateway/mcp-http.test.ts",
  "src/gateway/mention-directory.test.ts",
  "src/gateway/operator-approval-mcp-grants.test.ts",
  "src/gateway/server-close.agent-databases.test.ts",
  "src/gateway/server-methods/chat-send-synthetic-repair.integration.test.ts",
  "src/gateway/server-methods/chat.abort-live-proof.test.ts",
  "src/gateway/server-methods/chat.reset-visible-yield.test.ts",
  "src/gateway/server-methods/models-auth-login.catalog.integration.test.ts",
  "src/gateway/server-methods/models-auth-refresh.catalog.integration.test.ts",
  "src/gateway/server-methods/models-auth-refresh.integration.test.ts",
  "src/gateway/server-methods/models-auth-removal.integration.test.ts",
  "src/gateway/server-methods/models-connect-publication.integration.test.ts",
  "src/gateway/server-methods/models-dispatch.catalog.integration.test.ts",
  "src/gateway/server-methods/models-list.discovery-lifecycle.integration.test.ts",
  "src/gateway/server-methods/models-list.worker-recovery.integration.test.ts",
  "src/gateway/server-methods/session-catalog.performance.test.ts",
  "src/gateway/server-request-entry.test.ts",
  "src/gateway/server-sidecar-retention.test.ts",
  "src/gateway/server-startup-lifetime.test.ts",
  "src/gateway/server-startup-secret-owner-isolation.test.ts",
  "src/gateway/server-startup-workspace-readiness.test.ts",
  "src/gateway/server.agent-artifact-apis.test.ts",
  "src/gateway/server.auth.control-ui.test.ts",
  "src/gateway/server.chat-cli-auth.test.ts",
  "src/gateway/server.chat.acp-completion.test.ts",
  "src/gateway/server.chat.gateway-server-chat-b.test.ts",
  "src/gateway/server.hooks.test.ts",
  "src/gateway/server.models-native-retirement.test.ts",
  "src/gateway/server.placement-abandonment.test.ts",
  "src/gateway/server.sessions.compaction.test.ts",
  "src/gateway/server.sessions.create.accounts.test.ts",
  "src/gateway/server.sessions.create.workspace-policy.test.ts",
  "src/gateway/server.sessions.create.worktree-selection.test.ts",
  "src/gateway/server.sessions.create.worktrees.test.ts",
  "src/gateway/server.sessions.delete-lifecycle.test.ts",
  "src/gateway/server.sessions.fixture-lifecycle.test.ts",
  "src/gateway/server.sessions.store-paths.test.ts",
  "src/gateway/server.startup-fixture-lifetime.test.ts",
  "src/gateway/server.visible-spawn-fallback.product-proof.test.ts",
  "src/gateway/server.xai-fallback.test.ts",
  "src/gateway/session-activity-summaries.test.ts",
  "src/gateway/session-delivery-clock-jump.integration.test.ts",
  "src/gateway/session-message-events.test.ts",
  "src/gateway/session-repository-materialization.test.ts",
  "src/gateway/session-transcript-title-reader.test.ts",
  "src/gateway/sessions-history-http.physical-source.test.ts",
  "src/gateway/sessions-history-http.test.ts",
  "src/gateway/setup-inference.first-signin.integration.test.ts",
  "src/gateway/test-helpers.acquisition.test.ts",
  "src/gateway/watch-node-http.test.ts",
  "src/gateway/worker-environments/node-enrollment.test.ts",
  "src/gateway/worker-environments/node-worker-workspace-publication.test.ts",
  "src/gateway/worker-environments/prepared-environment-store.test.ts",
  "src/gateway/worker-environments/prepared-pool.test.ts",
  "src/gateway/worker-environments/provider-allocation-cleanup.test.ts",
  "src/gateway/worker-environments/provider-crabbox-runtime-preflight.test.ts",
  "src/gateway/worker-environments/repository-workspace-startup.test.ts",
  "src/gateway/worker-environments/skill-resource-transfer.test.ts",
  "src/gateway/worker-environments/worker-turn-execution.test.ts",
  "src/gateway/worker-environments/worker-turn-payload.test.ts",
  "src/gateway/worker-environments/workspace-sync-scripts.test.ts",
  "src/infra/outbound/deliver-queue.cancellation-integration.test.ts",
  "src/infra/outbound/deliver.queue-integration.test.ts",
  "src/infra/outbound/delivery-queue.reconnect-drain.test.ts",
  "src/infra/state-migrations.caller-mode.refusal.test.ts",
  "src/infra/state-migrations.caller-mode.storage.test.ts",
  "src/infra/state-migrations.skill-workshop.test.ts",
  "src/infra/update-candidate-state.test.ts",
  "src/infra/update-candidate-workspace-rehearsal.test.ts",
  "src/infra/update-managed-service-handoff-cross-process.test.ts",
  "src/infra/update-managed-service-handoff-terminal-result.test.ts",
  "src/snapshot/git-backup.test.ts",
  "src/state/agent-database-admission.test.ts",
  "src/state/openclaw-database-preflight.artifacts.test.ts",
  "src/tasks/task-registry-terminal-notification.test.ts",
  "src/transcripts/store.test.ts",
  "test/e2e/qa-lab/runtime/gateway-codex-delivery-cache.test.ts",
  "test/helpers/openclaw-test-instance.test.ts",
  "test/matrix-channel-read-authority.integration.test.ts",
  "test/non-isolated-runner.test.ts",
  "test/scripts/build-artifact-cache.test.ts",
  "test/scripts/ci-git-owner.test.ts",
  "test/scripts/ci-workflow-evidence.test.ts",
  "test/scripts/crabbox-hydrate-dependencies.test.ts",
  "test/scripts/docker-build-helper.test.ts",
  "test/scripts/lint-status.test.ts",
  "test/scripts/mobile-release-authority.test.ts",
  "test/scripts/npm-onboard-channel-agent-shell.test.ts",
  "test/scripts/openclaw-performance-git-lifecycle.test.ts",
  "test/scripts/plugin-release-git-lifecycle.test.ts",
  "test/scripts/pr-closeout-gates.test.ts",
  "test/scripts/pr-operation-lock.test.ts",
  "test/scripts/pr-worktree-containment.test.ts",
  "test/scripts/pr-worktree-evidence.test.ts",
  "test/scripts/preflight-frozen-target-contracts.test.ts",
  "test/scripts/prepare-extension-package-boundary-artifacts.test.ts",
  "test/scripts/profile-extension-memory.test.ts",
  "test/scripts/release-plan-producer.test.ts",
  "test/scripts/release-workflow-git-lifecycle.test.ts",
  "test/scripts/render-maturity-docs.test.ts",
  "test/scripts/telegram-e2e-userbot-skill.test.ts",
  "test/scripts/upgrade-survivor-baseline-order.test.ts",
  "test/scripts/upgrade-survivor-plugin-registry.test.ts",
  "test/scripts/validate-release-publish-approval.test.ts",
  "test/scripts/vitest-fork-shutdown.test.ts",
  "test/scripts/vitest-forks-pool.test.ts",
  "test/scripts/vitest-worker-artifacts.ci.test.ts",
  "test/scripts/vitest-worker-shutdown.test.ts",
  "test/scripts/write-plugin-sdk-entry-dts.test.ts",
  "test/scripts/write-unified-entry-dts.test.ts",
  "test/telegram-outbound-permanent-rejection-loopback.test.ts",
  "test/telegram-recovery-notice-send.test.ts",
  "test/test-env.test.ts",
  "test/vitest-ui-e2e-config.test.ts",
  "ui/src/test-helpers/control-ui-e2e-suite.test.ts",
] as const;

const prExemptRuntimeTestFiles = new Set<string>(PR_EXEMPT_RUNTIME_TEST_FILES);

export function listPrExemptRuntimeTestFiles(cwd = process.cwd()): string[] {
  return PR_EXEMPT_RUNTIME_TEST_FILES.filter((file) =>
    statSync(resolve(cwd, file), { throwIfNoEntry: false })?.isFile(),
  );
}

export function isPrExemptRuntimeTestFile(file: string): boolean {
  return prExemptRuntimeTestFiles.has(file);
}
