// Public user-profile and self-service GitHub contracts.
export {
  GIT_COAUTHOR_PREFERENCE_KEY,
  isGitCoauthorCreditEnabled,
  normalizeUiAppearancePreference,
  UI_APPEARANCE_PREFERENCE_KEYS,
  UserProfileSchema,
  PersonalGitHubAccountSchema,
  PersonalGitHubGenerationSchema,
  PersonalGitHubStatusSchema,
  UsersGitHubStatusParamsSchema,
  UsersGitHubStatusResultSchema,
  UsersGitHubAuthorizeStartParamsSchema,
  UsersGitHubAuthorizeStartResultSchema,
  UsersGitHubAuthorizePollParamsSchema,
  UsersGitHubAuthorizePollResultSchema,
  UsersGitHubAuthorizeCancelParamsSchema,
  UsersGitHubAuthorizeCancelResultSchema,
  UsersGitHubDisconnectParamsSchema,
  UsersGitHubDisconnectResultSchema,
  UsersLinkEmailParamsSchema,
  UsersLinkEmailResultSchema,
  UsersListParamsSchema,
  UsersListResultSchema,
  UsersPrefsGetParamsSchema,
  UsersPrefsGetResultSchema,
  UsersPrefsChangedEventSchema,
  UsersPrefsSetParamsSchema,
  UsersPrefsSetResultSchema,
  UsersSelfParamsSchema,
  UsersSelfResultSchema,
  UsersSetAvatarParamsSchema,
  UsersSetAvatarResultSchema,
  UsersSetDisplayNameParamsSchema,
  UsersSetDisplayNameResultSchema,
  UsersSetRoleParamsSchema,
  UsersSetRoleResultSchema,
} from "./schema/users.js";
