// Lightweight in-memory queue for human-readable system events that should be
// prefixed to the next prompt. We intentionally avoid persistence to keep
// events ephemeral. Events are session-scoped and require an explicit key.

import {
  normalizeOptionalLowercaseString,
  normalizeOptionalString,
} from "@openclaw/normalization-core/string-coerce";
import { createSubsystemLogger } from "../logging/subsystem.js";
import { channelRouteDedupeKey } from "../plugin-sdk/channel-route.js";
import { parseAgentSessionKey } from "../routing/session-key.js";
import { resolveGlobalMap, resolveGlobalSingleton } from "../shared/global-singleton.js";
import {
  mergeDeliveryContext,
  normalizeDeliveryContext,
} from "../utils/delivery-context.shared.js";
import type { DeliveryContext } from "../utils/delivery-context.types.js";
import {
  execRequestMatches,
  readExecRequestOwners,
  withExecRequestOwners,
  type ExecRequestIdentity,
} from "./exec-request-context.js";
import { generateSecureUuid } from "./secure-random.js";
import {
  getSystemEventStorePath,
  isSystemEventStoreCurrent,
  registerSystemEventStoreOwner,
  recordSystemEventStoreReplaced,
} from "./system-event-ownership.js";

export type SystemEvent = {
  /**
   * OpenClaw-assigned opaque identity for one queued occurrence. Preserve it when returning a
   * snapshot to consume. It changes on replacement or re-enqueue; optional only for legacy
   * ID-less compatibility.
   */
  id?: string;
  text: string;
  ts: number;
  contextKey?: string | null;
  deliveryContext?: DeliveryContext;
  /** An unresolved exec attempt must not be regenerated by an unrelated model turn. */
  deliveryHeld?: boolean;
  /** Queued by work a conversation turn started, not heartbeat or automation work. */
  fromConversationTurn?: true;
  sessionStorePath?: string | null;
};

const MAX_EVENTS = 20;
const log = createSubsystemLogger("system-events");

export class SystemEventQueueFullError extends Error {
  constructor() {
    super(
      `System event queue is full (${MAX_EVENTS} pending). Let the session process pending events before retrying the notification.`,
    );
    this.name = "SystemEventQueueFullError";
  }
}

type SessionQueue = {
  queue: SystemEvent[];
  lastContextKey: string | null;
};

const SYSTEM_EVENT_QUEUES_KEY = Symbol.for("openclaw.systemEvents.queues");

const turnOwners = resolveGlobalSingleton(
  Symbol.for("openclaw.systemEvents.turnOwners"),
  () => new WeakMap<SystemEvent, { cancel: () => void; started: boolean }>(),
  (owners) => {
    // Soft restart retires admitted turns; unmigrated passive notices retain their queue.
    for (const [key, entry] of queues) {
      const removed = entry.queue.filter((event) => owners.has(event));
      entry.queue = entry.queue.filter((event) => !owners.has(event));
      resetQueueState(key, entry);
      retireSystemEvents(removed);
    }
  },
);

function retireSystemEvents(events: readonly SystemEvent[]): void {
  for (const event of events) {
    const owner = turnOwners.get(event);
    if (owner && !owner.started) {
      owner.cancel();
    }
  }
}

function clearSystemEventQueues(value: Map<string, SessionQueue>) {
  const removed = [...value.values()].flatMap((entry) => entry.queue.splice(0));
  value.clear();
  retireSystemEvents(removed);
}

const queues = resolveGlobalMap<string, SessionQueue>(
  SYSTEM_EVENT_QUEUES_KEY,
  clearSystemEventQueues,
  "close-only",
);
registerSystemEventStoreOwner(SYSTEM_EVENT_QUEUES_KEY, () => {
  for (const [key, entry] of queues) {
    const removed = entry.queue.filter(
      (event) => !isSystemEventStoreCurrent(key, event.sessionStorePath),
    );
    const retained = entry.queue.filter((event) =>
      isSystemEventStoreCurrent(key, event.sessionStorePath),
    );
    if (retained.length === entry.queue.length) {
      continue;
    }
    entry.queue = retained;
    resetQueueState(key, entry);
    retireSystemEvents(removed);
    recordSystemEventStoreReplaced();
  }
});

type SystemEventOptions = {
  sessionKey: string;
  sessionStorePath?: string | null;
  contextKey?: string | null;
  deliveryContext?: DeliveryContext;
  fromConversationTurn?: boolean;
  /** Replace the pending event for this context and delivery route. Requires contextKey. */
  replace?: boolean;
};

type ReceiptOptions = { allowDuplicate?: boolean };

function requireSessionKey(key?: string | null): string {
  const trimmed = normalizeOptionalString(key) ?? "";
  const parsed = parseAgentSessionKey(trimmed);
  if (!parsed) {
    throw new Error("system events require an agent-qualified sessionKey");
  }
  return `agent:${parsed.agentId}:${parsed.rest}`;
}

function normalizeContextKey(key?: string | null): string | null {
  return normalizeOptionalLowercaseString(key) ?? null;
}

function getSessionQueue(sessionKey: string): SessionQueue | undefined {
  const key = requireSessionKey(sessionKey);
  const entry = queues.get(key);
  if (entry) {
    const cancelled = entry.queue.filter((event) =>
      readExecRequestOwners(event)?.some((owner) => owner.signal.aborted),
    );
    if (cancelled.length > 0) {
      entry.queue = entry.queue.filter((event) => !cancelled.includes(event));
      resetQueueState(key, entry);
      retireSystemEvents(cancelled);
    }
  }
  return queues.get(key);
}

function getOrCreateSessionQueue(key: string): SessionQueue {
  const existing = getSessionQueue(key);
  if (existing) {
    return existing;
  }
  const created: SessionQueue = {
    queue: [],
    lastContextKey: null,
  };
  queues.set(key, created);
  return created;
}

function cloneSystemEvent(event: SystemEvent): SystemEvent {
  return {
    ...event,
    ...(event.deliveryContext ? { deliveryContext: { ...event.deliveryContext } } : {}),
  };
}

export function isSystemEventContextChanged(
  sessionKey: string,
  contextKey?: string | null,
): boolean {
  const existing = getSessionQueue(sessionKey);
  const normalized = normalizeContextKey(contextKey);
  return normalized !== (existing?.lastContextKey ?? null);
}

export function enqueueSystemEventEntry(
  text: string,
  options: SystemEventOptions,
  receiptOptions?: ReceiptOptions,
): SystemEvent | null {
  const event = enqueueOwnedSystemEventEntry(text, options, receiptOptions);
  return event ? cloneSystemEvent(event) : null;
}

/** Host-owned admission must report capacity refusal before claiming the occurrence. */
export function enqueueRequiredSystemEventEntry(
  text: string,
  options: SystemEventOptions,
  receiptOptions?: ReceiptOptions,
): SystemEvent | null {
  const event = enqueueOwnedSystemEventEntry(text, options, {
    ...receiptOptions,
    throwOnFull: true,
  });
  return event ? cloneSystemEvent(event) : null;
}

function enqueueOwnedSystemEventEntry(
  text: string,
  options: SystemEventOptions,
  receiptOptions?: ReceiptOptions & { throwOnFull?: boolean },
): SystemEvent | null {
  const key = requireSessionKey(options.sessionKey);
  if (readExecRequestOwners(options)?.some((owner) => owner.signal.aborted)) {
    return null;
  }
  const sessionStorePath =
    options.sessionStorePath === undefined
      ? getSystemEventStorePath(key)
      : options.sessionStorePath;
  if (!isSystemEventStoreCurrent(key, sessionStorePath)) {
    recordSystemEventStoreReplaced();
    return null;
  }
  const entry = getOrCreateSessionQueue(key);
  const cleaned = text.trim();
  if (!cleaned) {
    return null;
  }
  const normalizedContextKey = normalizeContextKey(options.contextKey);
  const normalizedDeliveryContext = normalizeDeliveryContext(options.deliveryContext);
  const matches = (event: SystemEvent) =>
    (event.contextKey ?? null) === normalizedContextKey &&
    areDeliveryContextsEqual(event.deliveryContext, normalizedDeliveryContext);
  if (options.replace) {
    if (normalizedContextKey === null) {
      throw new Error("replaced system events require a contextKey");
    }
    const matching = entry.queue.filter(matches);
    if (matching.length === 1 && matching[0]?.text === cleaned) {
      return null;
    }
  } else if (receiptOptions?.allowDuplicate !== true) {
    const duplicate = (event: SystemEvent | undefined) =>
      event !== undefined && event.text === cleaned && matches(event);
    if (
      normalizedContextKey === null ? duplicate(entry.queue.at(-1)) : entry.queue.some(duplicate)
    ) {
      return null;
    }
  }
  if (entry.queue.length >= MAX_EVENTS && !(options.replace && entry.queue.some(matches))) {
    const error = new SystemEventQueueFullError();
    log.warn(error.message, { sessionKey: key });
    if (receiptOptions?.throwOnFull) {
      throw error;
    }
    return null;
  }
  const replaced = options.replace ? entry.queue.filter(matches) : [];
  if (replaced.length > 0) {
    entry.queue = entry.queue.filter((event) => !matches(event));
  }
  if (normalizedContextKey !== null) {
    entry.lastContextKey = normalizedContextKey;
  }
  const event: SystemEvent = withExecRequestOwners(
    {
      id: generateSecureUuid(),
      text: cleaned,
      ts: Date.now(),
      ...(sessionStorePath === undefined ? {} : { sessionStorePath }),
      contextKey: normalizedContextKey,
      deliveryContext: normalizedDeliveryContext,
      ...(options.fromConversationTurn ? { fromConversationTurn: true as const } : {}),
    },
    readExecRequestOwners(options),
  );
  entry.queue.push(event);
  // Install the replacement before cancellation callbacks can enqueue more work.
  retireSystemEvents(replaced);
  return event;
}

export function enqueueSystemEvent(text: string, options: SystemEventOptions) {
  return enqueueOwnedSystemEventEntry(text, options) !== null;
}

/** Transfer one bounded set of exact occurrences to ordinary session admission. */
export function claimSystemEventTurn(
  sessionKey: string,
  occurrences: readonly SystemEvent[],
  cancel: () => void,
  agentId?: string,
) {
  const key = requireSessionKey(sessionKey);
  if (agentId && parseAgentSessionKey(key)?.agentId !== agentId) {
    return undefined;
  }
  const queue = getSessionQueue(key)?.queue;
  const ids = new Set(occurrences.map((occurrence) => occurrence.id));
  if (
    !queue ||
    ids.size === 0 ||
    ids.size > MAX_EVENTS ||
    ids.size !== occurrences.length ||
    ids.has(undefined)
  ) {
    return undefined;
  }
  const events: SystemEvent[] = [];
  for (const occurrence of occurrences) {
    const event = queue.find((entry) => entry.id === occurrence.id);
    if (!event || turnOwners.has(event)) {
      return undefined;
    }
    events.push(event);
  }
  let cancelled = false;
  const owner = {
    cancel: () => {
      if (!cancelled) {
        cancelled = true;
        cancel();
      }
    },
    started: false,
  };
  for (const event of events) {
    turnOwners.set(event, owner);
  }
  const currentEvents = () => {
    const current = getSessionQueue(key)?.queue;
    return owner.started
      ? []
      : events.filter((event) => turnOwners.get(event) === owner && current?.includes(event));
  };
  return {
    start() {
      if (currentEvents().length !== events.length) {
        throw new Error("Session event occurrence was cancelled before admission");
      }
      owner.started = true;
      consumeSelectedSystemEventEntries(key, events);
    },
    // A member can already be gone; settle every surviving claim without touching replacements.
    cancel: () => consumeSelectedSystemEventEntries(key, currentEvents()).length > 0,
    /** Rejected adoption returns the surviving originals to passive custody. */
    release() {
      const current = currentEvents();
      for (const event of current) {
        turnOwners.delete(event);
      }
      return current.length > 0;
    },
  };
}

export function isSystemEventTurnOwned(sessionKey: string, occurrence: SystemEvent): boolean {
  const event = getSessionQueue(sessionKey)?.queue.find((entry) => entry.id === occurrence.id);
  return event !== undefined && turnOwners.has(event);
}

/** Enqueues one occurrence and returns one-use removal ownership for its UUID. */
export function enqueueSystemEventWithReceipt(
  text: string,
  options: SystemEventOptions,
  receiptOptions?: ReceiptOptions,
): (() => boolean) | null {
  const event = enqueueOwnedSystemEventEntry(text, options, {
    ...receiptOptions,
    throwOnFull: true,
  });
  if (!event) {
    return null;
  }
  const sessionKey = requireSessionKey(options.sessionKey);
  return () => consumeSelectedSystemEventEntries(sessionKey, [event]).length > 0;
}

export function drainSystemEventEntries(sessionKey: string): SystemEvent[] {
  return drainSystemEventsWith(sessionKey, cloneSystemEvent);
}

function drainSystemEventsWith<T>(sessionKey: string, project: (event: SystemEvent) => T): T[] {
  const key = requireSessionKey(sessionKey);
  const entry = getSessionQueue(key);
  if (!entry || entry.queue.length === 0) {
    return [];
  }
  const removed = entry.queue.splice(0);
  entry.lastContextKey = null;
  queues.delete(key);
  retireSystemEvents(removed);
  return removed.map(project);
}

function areDeliveryContextsEqual(left?: DeliveryContext, right?: DeliveryContext): boolean {
  if (!left && !right) {
    return true;
  }
  if (!left || !right) {
    return false;
  }
  return channelRouteDedupeKey(left) === channelRouteDedupeKey(right);
}

function matchesConsumedSystemEvent(queued: SystemEvent, consumed: SystemEvent): boolean {
  if (consumed.id !== undefined) {
    // Queue-owned IDs govern modern consumption; only legacy ID-less snapshots use structure.
    return queued.id === consumed.id;
  }
  return (
    queued.text === consumed.text &&
    queued.ts === consumed.ts &&
    (queued.contextKey ?? null) === (consumed.contextKey ?? null) &&
    areDeliveryContextsEqual(queued.deliveryContext, consumed.deliveryContext)
  );
}

function resetQueueState(key: string, entry: SessionQueue) {
  if (entry.queue.length === 0) {
    entry.lastContextKey = null;
    queues.delete(key);
    return;
  }
  entry.lastContextKey =
    entry.queue.findLast((event) => event.contextKey != null)?.contextKey ?? null;
}

export function consumeSelectedSystemEventEntries(
  sessionKey: string,
  consumedEntries: readonly SystemEvent[],
  options?: { deferredEventIds?: readonly string[] },
): SystemEvent[] {
  const key = requireSessionKey(sessionKey);
  const entry = getSessionQueue(key);
  if (!entry || entry.queue.length === 0 || consumedEntries.length === 0) {
    return [];
  }
  // Prompt admission can defer captured occurrences to a delivery owner. Selection
  // still resolves against the live queue, in captured order, never late arrivals.
  const deferredIds = new Set(options?.deferredEventIds);
  const selected: SystemEvent[] = [];
  const retired: SystemEvent[] = [];
  for (const consumed of consumedEntries) {
    const index = entry.queue.findIndex((event) => matchesConsumedSystemEvent(event, consumed));
    if (index === -1) {
      continue;
    }
    const event = entry.queue[index];
    if (event) {
      if (!event.id || !deferredIds.has(event.id)) {
        entry.queue.splice(index, 1);
        retired.push(event);
      }
      selected.push(cloneSystemEvent(event));
    }
  }
  resetQueueState(key, entry);
  retireSystemEvents(retired);
  return selected;
}

export function drainSystemEvents(sessionKey: string): string[] {
  return drainSystemEventsWith(sessionKey, (event) => event.text);
}

export function peekSystemEventEntries(sessionKey: string): SystemEvent[] {
  return getSessionQueue(sessionKey)?.queue.map(cloneSystemEvent) ?? [];
}

/** Routed completions retain request ownership after process output expires. Stop is a cold path. */
export function peekExecRequestSystemEventEntries(
  target: ExecRequestIdentity,
): Array<{ sessionKey: string; events: SystemEvent[] }> {
  const selected = [];
  for (const sessionKey of queues.keys()) {
    const events = peekSystemEventEntries(sessionKey).filter((event) =>
      readExecRequestOwners(event)?.some((owner) => execRequestMatches(owner, target)),
    );
    if (events.length > 0) {
      selected.push({ sessionKey, events });
    }
  }
  return selected;
}

export function peekSystemEvents(sessionKey: string): string[] {
  return getSessionQueue(sessionKey)?.queue.map((event) => event.text) ?? [];
}

export function hasSystemEvents(sessionKey: string) {
  return (getSessionQueue(sessionKey)?.queue.length ?? 0) > 0;
}

export function resolveSystemEventDeliveryContext(
  events: readonly SystemEvent[],
): DeliveryContext | undefined {
  let resolved: DeliveryContext | undefined;
  for (const event of events) {
    resolved = mergeDeliveryContext(event.deliveryContext, resolved);
  }
  return resolved;
}

export function resetSystemEventsForTest() {
  clearSystemEventQueues(queues);
}

export function peekDeliverableSystemEventEntries(sessionKey: string): SystemEvent[] {
  return peekSystemEventEntries(sessionKey).filter(
    (event) => !event.deliveryHeld && !isSystemEventTurnOwned(sessionKey, event),
  );
}
export function holdSystemEventDelivery(
  sessionKey: string,
  attempted: readonly SystemEvent[],
): void {
  for (const event of getSessionQueue(sessionKey)?.queue ?? []) {
    if (attempted.some((candidate) => matchesConsumedSystemEvent(event, candidate))) {
      event.deliveryHeld = true;
    }
  }
}
